# Pandas 101

## Data Structure

### Series

In [296]:
import pandas as pd
from pandas import DataFrame, Series
import numpy as np

#### Default range index

In [297]:
obj=Series([1,3,-4,-8])
obj

0    1
1    3
2   -4
3   -8
dtype: int64

In [298]:
obj.values

array([ 1,  3, -4, -8])

In [299]:
obj.index

RangeIndex(start=0, stop=4, step=1)

#### Explicit index

In [300]:
obj2=Series([1,3,-4,-8],index=["a", "b", "c", "d"])
obj2

a    1
b    3
c   -4
d   -8
dtype: int64

In [301]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [302]:
obj2["a"]

1

In [303]:
obj2["d"]=6
obj2

a    1
b    3
c   -4
d    6
dtype: int64

#### numpy array like operations

In [304]:
obj2[['c', 'b', 'a']]

c   -4
b    3
a    1
dtype: int64

In [305]:
obj2[['c', 'b', 'a']]=[1,2,3]
obj2

a    3
b    2
c    1
d    6
dtype: int64

In [306]:
obj2[obj2>3]

d    6
dtype: int64

In [307]:
obj2*3

a     9
b     6
c     3
d    18
dtype: int64

In [308]:
obj2*=3
obj2

a     9
b     6
c     3
d    18
dtype: int64

In [309]:
np.exp(obj2)

a    8.103084e+03
b    4.034288e+02
c    2.008554e+01
d    6.565997e+07
dtype: float64

#### Create from dict

In [310]:
d = {"WA": 1000, "CA": 2000, "WY": 3000, "MD":4000}
obj3 = Series(d)
obj3

CA    2000
MD    4000
WA    1000
WY    3000
dtype: int64

##### Create with explicit index in a certain order

In [311]:
obj4=Series(d, index=["WA", "CA", "WY", "NY"])
obj4

WA    1000.0
CA    2000.0
WY    3000.0
NY       NaN
dtype: float64

In [312]:
pd.isnull(obj4)

WA    False
CA    False
WY    False
NY     True
dtype: bool

In [313]:
pd.notnull(obj4)

WA     True
CA     True
WY     True
NY    False
dtype: bool

In [314]:
obj4.isnull()

WA    False
CA    False
WY    False
NY     True
dtype: bool

In [315]:
obj4.notnull()

WA     True
CA     True
WY     True
NY    False
dtype: bool

In [316]:
obj3+obj4

CA    4000.0
MD       NaN
NY       NaN
WA    2000.0
WY    6000.0
dtype: float64

In [317]:
obj4.index

Index(['WA', 'CA', 'WY', 'NY'], dtype='object')

In [318]:
obj4.index.name="State"
obj4.index

Index(['WA', 'CA', 'WY', 'NY'], dtype='object', name='State')

In [319]:
obj4.name="Population"
obj4

State
WA    1000.0
CA    2000.0
WY    3000.0
NY       NaN
Name: Population, dtype: float64

In [320]:
obj.index=["WA", "WY", "CA", "NY"]
obj

WA    1
WY    3
CA   -4
NY   -8
dtype: int64

In [321]:
obj+obj4

CA    1996.0
NY       NaN
WA    1001.0
WY    3003.0
dtype: float64

### DataFrame

In [322]:
data = {
    "state": ["WA", "WA", "WA", "CA", "CA", "NY"],
    "year": [2000,2001,2002,1999,2000,2003],
    "pop": [1.2,3.4,2.4,3.2,4.5,4.5]
}
df = DataFrame(data)
df

pop state  year
0  1.2    WA  2000
1  3.4    WA  2001
2  2.4    WA  2002
3  3.2    CA  1999
4  4.5    CA  2000
5  4.5    NY  2003

In [323]:
df["pop"]

0    1.2
1    3.4
2    2.4
3    3.2
4    4.5
5    4.5
Name: pop, dtype: float64

In [324]:
df.head()

pop state  year
0  1.2    WA  2000
1  3.4    WA  2001
2  2.4    WA  2002
3  3.2    CA  1999
4  4.5    CA  2000

In [325]:
df=DataFrame(data, columns=['year','pop', 'state'])
df

year  pop state
0  2000  1.2    WA
1  2001  3.4    WA
2  2002  2.4    WA
3  1999  3.2    CA
4  2000  4.5    CA
5  2003  4.5    NY

In [326]:
df=DataFrame(data, columns=['year','pop', 'state', 'debt'], index=['zero','one', 'two', 'three', 'four', 'five'])
df

year  pop state debt
zero   2000  1.2    WA  NaN
one    2001  3.4    WA  NaN
two    2002  2.4    WA  NaN
three  1999  3.2    CA  NaN
four   2000  4.5    CA  NaN
five   2003  4.5    NY  NaN

In [327]:
df["year"]

zero     2000
one      2001
two      2002
three    1999
four     2000
five     2003
Name: year, dtype: int64

In [328]:
df.year

zero     2000
one      2001
two      2002
three    1999
four     2000
five     2003
Name: year, dtype: int64

In [329]:
df.loc['one']

year     2001
pop       3.4
state      WA
debt      NaN
Name: one, dtype: object

In [330]:
df['debt']=3
df

year  pop state  debt
zero   2000  1.2    WA     3
one    2001  3.4    WA     3
two    2002  2.4    WA     3
three  1999  3.2    CA     3
four   2000  4.5    CA     3
five   2003  4.5    NY     3

In [331]:
df['debt']=np.arange(6)
df

year  pop state  debt
zero   2000  1.2    WA     0
one    2001  3.4    WA     1
two    2002  2.4    WA     2
three  1999  3.2    CA     3
four   2000  4.5    CA     4
five   2003  4.5    NY     5

In [332]:
val=Series([3,8,9,100],index=['zero', 'two', 'five', 'eight'])
val

zero       3
two        8
five       9
eight    100
dtype: int64

In [333]:
df['debt']=val
df

year  pop state  debt
zero   2000  1.2    WA   3.0
one    2001  3.4    WA   NaN
two    2002  2.4    WA   8.0
three  1999  3.2    CA   NaN
four   2000  4.5    CA   NaN
five   2003  4.5    NY   9.0

In [334]:
df['eastern']=df['state']=='NY'
df

year  pop state  debt  eastern
zero   2000  1.2    WA   3.0    False
one    2001  3.4    WA   NaN    False
two    2002  2.4    WA   8.0    False
three  1999  3.2    CA   NaN    False
four   2000  4.5    CA   NaN    False
five   2003  4.5    NY   9.0     True

In [335]:
df.columns

Index(['year', 'pop', 'state', 'debt', 'eastern'], dtype='object')

In [336]:
del df['eastern']

In [337]:
df.columns

Index(['year', 'pop', 'state', 'debt'], dtype='object')

#### Create from nested dict

In [338]:
data2={'WA':{2000:1, 2001:2, 2003:3}, 'CA':{2000:3, 2001:3.5, 2002:4.0}}
df2=DataFrame(data2)
df2

CA   WA
2000  3.0  1.0
2001  3.5  2.0
2002  4.0  NaN
2003  NaN  3.0

In [339]:
df2.T

2000  2001  2002  2003
CA   3.0   3.5   4.0   NaN
WA   1.0   2.0   NaN   3.0

In [340]:
DataFrame(data2, index=[2004,2001,2000])

CA   WA
2004  NaN  NaN
2001  3.5  2.0
2000  3.0  1.0

In [341]:
pdata={'WA':df2['WA'][:-1], 'CA':df2['CA']}
df3=DataFrame(pdata)
df3

CA   WA
2000  3.0  1.0
2001  3.5  2.0
2002  4.0  NaN
2003  NaN  NaN

In [342]:
df3.index.name='year'
df3.columns.name='state'
df3

state   CA   WA
year           
2000   3.0  1.0
2001   3.5  2.0
2002   4.0  NaN
2003   NaN  NaN

In [343]:
df3.columns

Index(['CA', 'WA'], dtype='object', name='state')

In [344]:
df3.values

array([[ 3. ,  1. ],
       [ 3.5,  2. ],
       [ 4. ,  nan],
       [ nan,  nan]])

In [345]:
df2.values

array([[ 3. ,  1. ],
       [ 3.5,  2. ],
       [ 4. ,  nan],
       [ nan,  3. ]])

In [346]:
df.values

array([[2000, 1.2, 'WA', 3.0],
       [2001, 3.4, 'WA', nan],
       [2002, 2.4, 'WA', 8.0],
       [1999, 3.2, 'CA', nan],
       [2000, 4.5, 'CA', nan],
       [2003, 4.5, 'NY', 9.0]], dtype=object)

### Index

|Function|Description|
|--|--|
|append||
|difference||
|intersection||
|isin||
|delete||
|drop||
|insert||
|is_monotonic||
|is_unique||
|unique||


In [347]:
obj=Series(range(3), index=['a','b','c'])
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [348]:
'a' in obj.index

True

In [349]:
'g' in obj.index

False

In [350]:
obj.index[1:]

Index(['b', 'c'], dtype='object')

In [351]:
labels=pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [352]:
index=pd.RangeIndex(3)
index

RangeIndex(start=0, stop=3, step=1)

In [353]:
obj.index=index

In [354]:
obj

0    0
1    1
2    2
dtype: int64

In [355]:
labels.append(index)

Int64Index([0, 1, 2, 0, 1, 2], dtype='int64')

In [356]:
index2=pd.RangeIndex(2,8,1)

In [357]:
index.intersection(index2)

RangeIndex(start=2, stop=3, step=1)

In [358]:
labels.intersection(index2)

Int64Index([2], dtype='int64')

In [359]:
labels.union(index2)

Int64Index([0, 1, 2, 3, 4, 5, 6, 7], dtype='int64')

In [360]:
index.union(index2)

RangeIndex(start=0, stop=8, step=1)

In [361]:
index.union(pd.RangeIndex(10,20,2))

Int64Index([0, 1, 2, 10, 12, 14, 16, 18], dtype='int64')

In [362]:
index.difference(index2)

Int64Index([0, 1], dtype='int64')

In [363]:
index.isin(index2)

array([False, False,  True], dtype=bool)

In [364]:
index.delete(2)

Int64Index([0, 1], dtype='int64')

In [365]:
index2.delete(2)

Int64Index([2, 3, 5, 6, 7], dtype='int64')

In [366]:
index.drop(index2)

ValueError: labels [3 4 5 6 7] not contained in axis

In [ ]:
index3=pd.Index([0,2])
index.drop(index3)

In [ ]:
index.insert(0, -2)

In [ ]:
index.is_monotonic

In [ ]:
index.insert(0, 8).is_monotonic

In [ ]:
index.is_unique

In [ ]:
index.insert(0,2).is_unique

In [ ]:
index.insert(0,2).unique()

In [ ]:
for i in index:
    print(i)

## Basic features

## Reindex

In [ ]:
obj=Series([1.,2.,4.], index=['a','b','d'])
obj

In [ ]:
obj2=obj.reindex(['d','b','a','c'])
obj2

In [ ]:
obj3=obj.reindex(['d','b','a','c'], method='ffill')
obj3

In [ ]:
states=['WA','CA','NY']
df=DataFrame(np.random.randint(20,size=(3,3)), index=['a','c','d'], columns=states)
df

In [ ]:
df2=df.reindex(['a','b','c','d'])
df2

In [ ]:
new_states=['WA','AZ','TX']
df3=df.reindex(columns=new_states)
df3

In [ ]:
df.loc[['a','b','c','d'],['WA']]

## Drop data

In [ ]:
obj=DataFrame(np.arange(5.),index=['a','b','c','d','e'])
obj

In [ ]:
obj.drop('c')

In [ ]:
obj.drop(['d','b'])

In [ ]:
states=['WA','CA','NY']
df=DataFrame(np.random.randint(20,size=(3,3)), index=['a','c','d'], columns=states)
df

In [ ]:
df.drop('a')

In [ ]:
df.drop('WA', axis=1)

In [ ]:
df.drop(['CA', 'NY'],axis='columns')

In [ ]:
df

In [ ]:
df.drop(['CA'], axis='columns',inplace=True)
df

### Index, select and filter

In [ ]:
obj=Series(np.arange(4.),index=['a','b','c','d'])
obj[0:3]

In [ ]:
obj['a':'c']

In [ ]:
robj=obj.reindex(['a','c','d','b'])
robj

In [ ]:
robj['b':'c']

In [ ]:
robj['a':'b']

In [ ]:
robj['a':'c']

In [ ]:
obj2=Series(np.arange(4.))
obj2[0:3]

In [ ]:
obj2[0:1]=4
obj2

In [ ]:
df=DataFrame(np.random.randint(20,size=(4,4)), index=['WA','CA', 'NY', 'TX'],columns=['one','two','three','four'])
df

In [ ]:
df['one']

In [ ]:
df[['one','two']]

In [ ]:
df[0:4:2]

In [ ]:
df[df['one']>5]

In [ ]:
df.loc[['WA','CA'], 'one']

In [ ]:
df.loc['WA':'NY', 'one':'three']

In [ ]:
df.iloc[0:2]

In [ ]:
df.iloc[:,0:4:2][df['one']>5]

In [ ]:
df.iat[0,0]

In [ ]:
df.at['CA','one']

### Int Index

In [ ]:
ser = Series(np.arange(3.))
ser[-1]

In [ ]:
ser

In [ ]:
ser.iloc[-1]

### Arithmetic and data fill

In [ ]:
s1=Series(np.arange(3.), index=list('abc'))
s1

In [ ]:
s2=Series(np.arange(5.),index=list('cdefb'))
s2

In [ ]:
s1+s2

In [ ]:
s1*s2

In [ ]:
s1.add(s2,fill_value=0)

In [ ]:
s1.mul(s2, fill_value=1)

In [ ]:
df1=DataFrame(np.random.randint(20,size=(3,3)), index='WA,CA,NY'.split(','),columns=list('bac'))
df1

In [ ]:
df2=DataFrame(np.random.randint(20,size=(4,4)),index='WA,OH,CA,NY'.split(','), columns=list('aecd'))
df2

In [ ]:
df1+df2

In [ ]:
df1.add(df2,fill_value=0)

In [ ]:
1/df1

In [ ]:
df1.rdiv(1)

In [ ]:
ser=df1.iloc[0]
ser

In [ ]:
df1-ser

In [ ]:
ser2=Series(np.arange(5.), index=list('cafed'))
ser2

In [ ]:
df1-ser2

In [ ]:
df1

In [ ]:
ser3=Series(np.arange(5.), 'WA,CA,TX,OH,FL'.split(','))
ser3

In [ ]:
df1.sub(ser3, axis=0)

## Function

In [ ]:
df=DataFrame(np.random.randint(20,size=(4,4)), index=['WA','CA', 'NY', 'TX'],columns=['one','two','three','four'])
df

In [ ]:
np.sin(df)

In [ ]:
df.apply(np.sum)

In [ ]:
df.apply(np.sum,axis=1)

In [ ]:
df.sum()

In [ ]:
df.sum(axis=1)

In [ ]:
def f(x):
    return Series([x.min(),x.max()],index=['min','max'])

In [ ]:
df.apply(f)

In [ ]:
df.apply(f,axis=1)

In [ ]:
def fmt(x):
    return "%04d" % x
df.applymap(fmt)

In [ ]:
df['one'].map(fmt)

## Sort and rank

In [ ]:
df=DataFrame(np.random.randint(20,size=(4,4)), index=['WA','CA', 'NY', 'TX'],columns=['one','two','three','four'])
df

In [ ]:
df.sort_index()

In [ ]:
df.sort_index(axis=1)

In [ ]:
df.sort_values(by='two')

In [ ]:
one=df['one'].copy()
one

In [ ]:
one.sort_index()

In [ ]:
one.sort_values(ascending=False)

In [ ]:
df.sort_values(by=['two', 'one'])

In [ ]:
df.sort_values(axis=1, by='WA')

In [ ]:
obj=Series([1,2.,np.nan,-10])
obj

In [ ]:
obj.sort_values()

In [ ]:
obj.sort_values(ascending=False)

In [ ]:
obj = Series([7,0,7,0,2,-3])
obj.rank()

In [ ]:
obj.rank(method='first')

In [ ]:
obj.rank(method='min')

In [ ]:
obj.rank(method='max')

In [ ]:
obj.rank(method='dense')

### Dup index

In [ ]:
obj=Series(np.arange(5.),index=list('aabbc'))
obj

In [ ]:
obj['a']

In [ ]:
obj['c']

In [ ]:
df=DataFrame(np.random.randint(20,size=(5,5)), index=list('abcba'), columns='one,two,three,two,one'.split(','))
df

In [ ]:
df['one']

In [ ]:
df['three']

In [ ]:
df.loc['a']

In [ ]:
df.loc['c']

## Stat and describ

In [ ]:
df=DataFrame(np.random.randint(20,size=(5,5)), index=list('abcba'), columns='one,two,three,two,one'.split(','))
df

In [ ]:
df.describe()

In [ ]:
df.idxmax()

## Correlation

In [367]:
import pandas_datareader.data as web

In [368]:
all_data = {ticker:web.get_data_yahoo(ticker) for ticker in ['IBM', 'AAPL', 'MSFT',"AMZN"]}

In [369]:
all_data

{'AAPL':                   High         Low        Open       Close       Volume  \
 Date                                                                      
 2014-12-29  114.769997  113.699997  113.790001  113.910004   27598900.0   
 2014-12-30  113.919998  112.110001  113.639999  112.519997   29881500.0   
 2014-12-31  113.129997  110.209999  112.820000  110.379997   41403400.0   
 2015-01-02  111.440002  107.349998  111.389999  109.330002   53204600.0   
 2015-01-05  108.650002  105.410004  108.290001  106.250000   64285500.0   
 2015-01-06  107.430000  104.629997  106.540001  106.260002   65797100.0   
 2015-01-07  108.199997  106.699997  107.199997  107.750000   40105900.0   
 2015-01-08  112.150002  108.699997  109.230003  111.889999   59364500.0   
 2015-01-09  113.250000  110.209999  112.669998  112.010002   53699500.0   
 2015-01-12  112.629997  108.800003  112.599998  109.250000   49650800.0   
 2015-01-13  112.800003  108.910004  111.430000  110.220001   67091900.0   
 201

In [371]:
prices=DataFrame({ticker:data['Close'] for ticker, data in all_data.items()})
prices

AAPL         AMZN         IBM        MSFT
Date                                                       
2014-12-29  113.910004   312.040009  160.509995   47.450001
2014-12-30  112.519997   310.299988  160.050003   47.020000
2014-12-31  110.379997   310.350006  160.440002   46.450001
2015-01-02  109.330002   308.519989  162.059998   46.759998
2015-01-05  106.250000   302.190002  159.509995   46.330002
2015-01-06  106.260002   295.290009  156.070007   45.650002
2015-01-07  107.750000   298.420013  155.050003   46.230000
2015-01-08  111.889999   300.459991  158.419998   47.590000
2015-01-09  112.010002   296.929993  159.110001   47.189999
2015-01-12  109.250000   291.410004  156.440002   46.599998
2015-01-13  110.220001   294.739990  156.809998   46.360001
2015-01-14  109.800003   293.269989  155.800003   45.959999
2015-01-15  106.820000   286.950012  154.570007   45.480000
2015-01-16  105.989998   290.739990  157.139999   46.240002
2015-01-20  108.720001   289.440002  156.949997   46.389999
2015-01-21  109.550003   297.250000  152.089996   45.919998
2015-01-22  112.400002   310.320007  155.389999   47.130001
2015-01-23  112.980003   312.390015  155.869995   47.180000
2015-01-26  113.099998   309.660004  156.360001   47.009998
2015-01-27  109.139999   306.750000  153.669998   42.660000
2015-01-28  115.309998   303.910004  151.550003   41.189999
2015-01-29  118.900002   311.779999  155.479996   42.009998
2015-01-30  117.160004   354.529999  153.309998   40.400002
2015-02-02  118.629997   364.470001  154.660004   41.279999
2015-02-03  118.650002   363.549988  158.470001   41.599998
2015-02-04  119.559998   364.750000  156.960007   41.840000
2015-02-05  119.940002   373.890015  157.910004   42.450001
2015-02-06  118.930000   374.279999  156.720001   42.410000
2015-02-09  119.720001   370.559998  155.750000   42.360001
2015-02-10  122.019997   373.000000  158.559998   42.599998
...                ...          ...         ...         ...
2019-11-14  262.640015  1754.599976  134.000000  148.059998
2019-11-15  265.760010  1739.489990  134.399994  149.970001
2019-11-18  267.100006  1752.530029  134.309998  150.339996
2019-11-19  266.290009  1752.790039  134.520004  150.389999
2019-11-20  263.190002  1745.530029  133.199997  149.619995
2019-11-21  262.010010  1734.709961  133.839996  149.479996
2019-11-22  261.779999  1745.719971  134.339996  149.589996
2019-11-25  266.369995  1773.839966  135.970001  151.229996
2019-11-26  264.290009  1796.939941  135.089996  152.029999
2019-11-27  267.839996  1818.510010  133.770004  152.320007
2019-11-29  267.250000  1800.800049  134.449997  151.380005
2019-12-02  264.160004  1781.599976  132.910004  149.550003
2019-12-03  259.450012  1769.959961  132.119995  149.309998
2019-12-04  261.739990  1760.689941  131.990005  149.850006
2019-12-05  265.579987  1740.479980  131.910004  149.929993
2019-12-06  270.709991  1751.599976  133.220001  151.750000
2019-12-09  266.920013  1749.510010  133.919998  151.360001
2019-12-10  268.480011  1739.209961  133.910004  151.130005
2019-12-11  270.769989  1748.719971  133.759995  151.699997
2019-12-12  271.459991  1760.329956  135.320007  153.240005
2019-12-13  275.149994  1760.939941  134.210007  154.529999
2019-12-16  279.859985  1769.209961  134.130005  155.529999
2019-12-17  280.410004  1790.660034  134.220001  154.690002
2019-12-18  279.739990  1784.030029  134.410004  154.369995
2019-12-19  280.019989  1792.280029  134.559998  155.710007
2019-12-20  279.440002  1786.500000  135.589996  157.410004
2019-12-23  284.000000  1793.000000  135.550003  157.410004
2019-12-24  284.269989  1789.209961  134.979996  157.380005
2019-12-26  289.910004  1868.770020  134.910004  158.669998
2019-12-27  289.799988  1869.800049  135.270004  158.960007

[1259 rows x 4 columns]

In [374]:
volumns=DataFrame({ticker:data['Volume'] for ticker, data in all_data.items()})
volumns

AAPL      AMZN         IBM         MSFT
Date                                                      
2014-12-29   27598900.0   3009000   3331800.0   14439500.0
2014-12-30   29881500.0   2093000   2829900.0   16384700.0
2014-12-31   41403400.0   2048000   4011900.0   21552500.0
2015-01-02   53204600.0   2783200   5525500.0   27913900.0
2015-01-05   64285500.0   2774200   4880400.0   39673900.0
2015-01-06   65797100.0   3519000   6146700.0   36447900.0
2015-01-07   40105900.0   2640300   4701800.0   29114100.0
2015-01-08   59364500.0   3088400   4236800.0   29645200.0
2015-01-09   53699500.0   2592400   4488300.0   23944200.0
2015-01-12   49650800.0   3421400   4187600.0   23651900.0
2015-01-13   67091900.0   4136400   4377500.0   35270600.0
2015-01-14   48956600.0   5538700   4690300.0   29719600.0
2015-01-15   60014000.0   4419200   4248400.0   32750800.0
2015-01-16   78513300.0   3478200   5756000.0   35695300.0
2015-01-20   49899900.0   3075100   8392800.0   36161900.0
2015-01-21   48575900.0  10065100  11897100.0   39081100.0
2015-01-22   53796400.0   5362600   6120100.0   35898000.0
2015-01-23   46464800.0   4496400   4834800.0   26211600.0
2015-01-26   55615000.0   3169700   7888100.0   42525500.0
2015-01-27   95568700.0   2920300   5659600.0  169164000.0
2015-01-28  146477100.0   3063800   4495900.0   84507100.0
2015-01-29   84436400.0   8656600   8320800.0   63585300.0
2015-01-30   83745500.0  23856100   6563600.0   78004900.0
2015-02-02   62739100.0  10231900   4712200.0   50352500.0
2015-02-03   51915700.0   6212600   5539400.0   52082400.0
2015-02-04   70149700.0   4169900   3678500.0   41614800.0
2015-02-05   42246200.0   7247600   5253600.0   36548200.0
2015-02-06   43706600.0   3892400   3256500.0   34616600.0
2015-02-09   38889800.0   2724600   3057700.0   31381100.0
2015-02-10   62008500.0   2287200   4440600.0   29670700.0
...                 ...       ...         ...          ...
2019-11-14   22295700.0   2264800   4231300.0   19729800.0
2019-11-15   25051600.0   3927600   3262500.0   23485700.0
2019-11-18   21675800.0   2839500   3210400.0   21534000.0
2019-11-19   19041800.0   2270800   2995000.0   23935700.0
2019-11-20   26558600.0   2790000   4138200.0   25696800.0
2019-11-21   30348800.0   2662900   3345300.0   18576100.0
2019-11-22   16331300.0   2479100   3297500.0   15901800.0
2019-11-25   21005100.0   3486200   2590100.0   22420900.0
2019-11-26   26301900.0   3181200   3793200.0   24620100.0
2019-11-27   16308900.0   3025600   3280900.0   15184400.0
2019-11-29   11654400.0   1923400   1825300.0   11977300.0
2019-12-02   23621800.0   3925600   3067100.0   27418400.0
2019-12-03   28607600.0   3380900   3642500.0   24066000.0
2019-12-04   16795400.0   2670100   3530000.0   17574700.0
2019-12-05   18606100.0   2823800   3595400.0   17869100.0
2019-12-06   26518900.0   3117400   3437500.0   16403500.0
2019-12-09   32010600.0   2442800   2968500.0   16687400.0
2019-12-10   22605100.0   2514300   3480400.0   16476100.0
2019-12-11   19689200.0   2097600   3953300.0   18856600.0
2019-12-12   34327600.0   3095900   4824100.0   24612100.0
2019-12-13   33396900.0   2745700   2535000.0   23845400.0
2019-12-16   32046500.0   3145200   3049200.0   24144200.0
2019-12-17   28539600.0   3644400   2907200.0   25425600.0
2019-12-18   29007100.0   3351400   3101800.0   24129200.0
2019-12-19   24592300.0   2652800   3866500.0   24958900.0
2019-12-20   68994500.0   5150800   7111800.0   53477500.0
2019-12-23   24643000.0   2136400   2803200.0   17718200.0
2019-12-24   12119700.0    881300   1202100.0    8989200.0
2019-12-26   23280300.0   6005400   2129700.0   14520600.0
2019-12-27   36566500.0   6186600   2752200.0   18412800.0

[1259 rows x 4 columns]

In [376]:
prices.pct_change().tail()

AAPL      AMZN       IBM      MSFT
Date                                              
2019-12-20 -0.002071 -0.003225  0.007655  0.010918
2019-12-23  0.016318  0.003638 -0.000295  0.000000
2019-12-24  0.000951 -0.002114 -0.004205 -0.000191
2019-12-26  0.019840  0.044467 -0.000519  0.008197
2019-12-27 -0.000379  0.000551  0.002668  0.001828

In [377]:
def minmax(x):
    return Series([x.min(),x.max()], index=['min','max'])

In [378]:
prices.apply(minmax)

AAPL         AMZN         IBM        MSFT
min   90.339996   286.950012  107.570000   40.290001
max  289.910004  2039.510010  181.949997  158.960007

In [379]:
changes=prices.pct_change()

In [380]:
changes.corrwith(changes.AMZN)

AAPL    0.493042
AMZN    1.000000
IBM     0.332985
MSFT    0.625252
dtype: float64

In [382]:
prices.apply(pd.value_counts)

AAPL  AMZN  IBM  MSFT
40.290001     NaN   NaN  NaN   1.0
40.400002     NaN   NaN  NaN   1.0
40.470001     NaN   NaN  NaN   1.0
40.660000     NaN   NaN  NaN   1.0
40.720001     NaN   NaN  NaN   1.0
40.959999     NaN   NaN  NaN   1.0
40.970001     NaN   NaN  NaN   1.0
41.020000     NaN   NaN  NaN   1.0
41.189999     NaN   NaN  NaN   1.0
41.209999     NaN   NaN  NaN   1.0
41.279999     NaN   NaN  NaN   1.0
41.380001     NaN   NaN  NaN   1.0
41.419998     NaN   NaN  NaN   1.0
41.459999     NaN   NaN  NaN   1.0
41.480000     NaN   NaN  NaN   1.0
41.529999     NaN   NaN  NaN   1.0
41.549999     NaN   NaN  NaN   1.0
41.560001     NaN   NaN  NaN   1.0
41.599998     NaN   NaN  NaN   1.0
41.619999     NaN   NaN  NaN   1.0
41.650002     NaN   NaN  NaN   1.0
41.680000     NaN   NaN  NaN   1.0
41.700001     NaN   NaN  NaN   1.0
41.720001     NaN   NaN  NaN   1.0
41.759998     NaN   NaN  NaN   1.0
41.820000     NaN   NaN  NaN   1.0
41.840000     NaN   NaN  NaN   1.0
41.980000     NaN   NaN  NaN   1.0
42.009998     NaN   NaN  NaN   1.0
42.029999     NaN   NaN  NaN   1.0
...           ...   ...  ...   ...
1958.310059   NaN   1.0  NaN   NaN
1962.459961   NaN   1.0  NaN   NaN
1964.520020   NaN   1.0  NaN   NaN
1970.189941   NaN   1.0  NaN   NaN
1971.310059   NaN   1.0  NaN   NaN
1973.819946   NaN   1.0  NaN   NaN
1974.550049   NaN   1.0  NaN   NaN
1974.849976   NaN   1.0  NaN   NaN
1977.900024   NaN   1.0  NaN   NaN
1985.630005   NaN   1.0  NaN   NaN
1987.150024   NaN   1.0  NaN   NaN
1988.300049   NaN   1.0  NaN   NaN
1989.869995   NaN   1.0  NaN   NaN
1990.000000   NaN   1.0  NaN   NaN
1992.030029   NaN   1.0  NaN   NaN
1994.489990   NaN   1.0  NaN   NaN
1994.819946   NaN   1.0  NaN   NaN
1998.099976   NaN   1.0  NaN   NaN
2000.810059   NaN   1.0  NaN   NaN
2001.069946   NaN   1.0  NaN   NaN
2002.380005   NaN   1.0  NaN   NaN
2003.000000   NaN   1.0  NaN   NaN
2004.359985   NaN   1.0  NaN   NaN
2009.900024   NaN   1.0  NaN   NaN
2011.000000   NaN   1.0  NaN   NaN
2012.709961   NaN   1.0  NaN   NaN
2012.979980   NaN   1.0  NaN   NaN
2017.410034   NaN   1.0  NaN   NaN
2020.989990   NaN   1.0  NaN   NaN
2039.510010   NaN   1.0  NaN   NaN

[4516 rows x 4 columns]